[env]
board_build.filesystem = littlefs
framework = arduino
upload_speed = 921600
extra_scripts = pre:pre_script.py
lib_deps =
    sstaub/Ticker@^4.4.0
    bblanchon/ArduinoJson@^7.2.0
    marvinroger/AsyncMqttClient@^0.9.0
    esp32async/ESPAsyncWebServer@^3.10.3
    arduino-libraries/NTPClient@^3.2.1

[esp8266]
platform = espressif8266
board = esp12e
lib_deps =
    ${env.lib_deps}
    esp32async/ESPAsyncTCP@^2.0.0

[esp32]
platform = espressif32
board = esp32dev
lib_deps =
    ${env.lib_deps}
    esp32async/AsyncTCP@^3.4.10

[release]
extra_scripts =
    ${env.extra_scripts}
    post:post_script.py

[env:esp_fleurie]
platform = ${esp8266.platform}
board = ${esp8266.board}
lib_deps = ${esp8266.lib_deps}
extra_scripts = ${release.extra_scripts}
build_flags = -D FLEURIE

[env:esp_pixie]
platform = ${esp8266.platform}
board = ${esp8266.board}
lib_deps = ${esp8266.lib_deps}
extra_scripts = ${release.extra_scripts}
build_flags = -D PIXIE

[env:esp32_fleurie]
platform = ${esp32.platform}
board = ${esp32.board}
lib_deps = ${esp32.lib_deps}
extra_scripts = ${release.extra_scripts}
build_flags = -D FLEURIE -D ESP32

[env:esp32_pixie]
platform = ${esp32.platform}
board = ${esp32.board}
lib_deps = ${esp32.lib_deps}
extra_scripts = ${release.extra_scripts}
build_flags = -D PIXIE -D ESP32

; [env:esp_pixie_512k]
; platform = ${esp8266.platform}
; lib_deps = ${esp8266.lib_deps}
; extra_scripts = ${release.extra_scripts}
; board = esp01
; build_flags = -D PIXIE

[env:esp_fleurie_debug]
platform = ${esp8266.platform}
board = ${esp8266.board}
lib_deps = ${esp8266.lib_deps}
monitor_speed  = 115200
build_flags = -D FLEURIE -D DEBUG

[env:esp_pixie_debug]
platform = ${esp8266.platform}
board = ${esp8266.board}
lib_deps = ${esp8266.lib_deps}
monitor_speed  = 115200
build_flags = -D PIXIE -D DEBUG

[env:esp32_fleurie_debug]
platform = ${esp32.platform}
board = ${esp32.board}
lib_deps = ${esp32.lib_deps}
monitor_speed  = 115200
extra_scripts = ${release.extra_scripts}
build_flags = -D FLEURIE -D ESP32 -D DEBUG

[env:esp32_pixie_debug]
platform = ${esp32.platform}
board = ${esp32.board}
lib_deps = ${esp32.lib_deps}
monitor_speed  = 115200
extra_scripts = ${release.extra_scripts}
build_flags = -D PIXIE -D ESP32 -D DEBUG